import React from "react";

import Boar from "../assets/emojis/boar.png";
import Crocodile from "../assets/emojis/crocodile.png";
import Cyclone from "../assets/emojis/cyclone.png";
import Duck from "../assets/emojis/duck.png";
import Corn from "../assets/emojis/ear-of-corn.png";
import Chick from "../assets/emojis/front-facing-baby-chick.png";
import Frog from "../assets/emojis/frog.png";
import Gorilla from "../assets/emojis/gorilla.png";
import Honeybee from "../assets/emojis/honeybee.png";
import HotSprings from "../assets/emojis/hot-springs.png";
import Chef from "../assets/emojis/chef.png";
import Mushroom from "../assets/emojis/mushroom.png";
import Ox from "../assets/emojis/ox.png";
import Rhinoceros from "../assets/emojis/rhinoceros.png";
import Yam from "../assets/emojis/roasted-sweet-potato.png";
import Shark from "../assets/emojis/shark.png";
import Shield from "../assets/emojis/shield.png";
import Snail from "../assets/emojis/snail.png";
import Snake from "../assets/emojis/snake.png";
import Squid from "../assets/emojis/squid.png";
import Sushi from "../assets/emojis/sushi.png";
import TRex from "../assets/emojis/t-rex.png";
import Turtle from "../assets/emojis/turtle.png";
import Unicorn from "../assets/emojis/unicorn.png";
import Whale from "../assets/emojis/whale.png";

export const emojis = {
  Boar,
  Crocodile,
  Cyclone,
  Duck,
  Corn,
  Chick,
  Frog,
  Gorilla,
  Honeybee,
  HotSprings,
  Chef,
  Mushroom,
  Ox,
  Rhinoceros,
  Yam,
  Shark,
  Shield,
  Snail,
  Snake,
  Squid,
  Sushi,
  TRex,
  Turtle,
  Unicorn,
  Whale,
};

const menuSetup = {
  onsen: [
    33,
    36,
    31,
    22,
    53,
    63,
    //64,
    65,
    69,
    83,
    85,
    96,
    35,
    42,
    66,
    67,
    70,
    71,
    99,
    73,
    75,
    81,
    82,
    86,
    92,
    95,
    98,
    48,
    59,
    68,
    72,
    74,
    76,
    77,
    78,
    79,
    80,
    84,
    87,
    88,
    89,
    90,
    91,
    93,
    94,
    97,
    100,
  ],
  upcoming: [],
  previous: [
    10,
    15,
    19,
    20,
    //22,
    23,
    24,
    25,
    26,
    27,
    28,
    //31,
    32,
    //33,
    34,
    //35,
    //36,
    38,
    39,
    40,
    41,
    //42,
    43,
    46,
    47,
    //48,
    49,
    50,
    51,
    52,
    //53,
    54,
    55,
    56,
    57,
    //58,
    //59,
    60,
  ],
  permanent: [12, 58, 25, 1, 2, 21, 0, 11, 3, 8, 37, 4, 6, 7, 9, 18, 44, 13, 17, 101],
};

export const menus = {
  onsen: menuSetup.onsen.sort((a, b) => a - b),
  upcoming: menuSetup.upcoming.sort((a, b) => a - b),
  previous: menuSetup.previous.sort((a, b) => a - b), // previous now overridden by any pool with allocPoint === 0
  permanent: menuSetup.permanent.sort((a, b) => a - b),
  active: menuSetup.permanent.concat(menuSetup.onsen).reduce(function(a, b) {
    if (a.indexOf(b) < 0) a.push(b);
    return a;
  }, []),
};

// For tokens that suffer a protocol exploit and need a warning
export const TOKEN_WARNINGS = [
  "0x5d8d9f5b96f4438195be9b99eee6118ed4304286", // COVER
];

export const FARM_DETAILS = [
  { pid: 0, name: "Tether Turtle", symbol: "USDT-ETH SLP", icon: "Turtle" },
  { pid: 1, name: "Circle Snail", symbol: "USDC-ETH SLP", icon: "Snail" },
  { pid: 2, name: "Donald DAI", symbol: "DAI-ETH SLP", icon: "Duck" },
  { pid: 3, name: "Spartan Dollar", symbol: "SUSD-ETH SLP", icon: "Gorilla" },
  { pid: 4, name: "Comp Truffle", symbol: "COMP-ETH SLP", icon: "Mushroom" },
  { pid: 5, name: "LEND (Old)", symbol: "LEND-ETH SLP", icon: "Boar" },
  { pid: 6, name: "Synth Snake", symbol: "SNX-ETH SLP", icon: "Snake" },
  { pid: 7, name: "Umami Squid", symbol: "UMA-ETH SLP", icon: "Squid" },
  { pid: 8, name: "Toadie Marine", symbol: "LINK-ETH SLP", icon: "Frog" },
  { pid: 9, name: "Band-osaurus", symbol: "BAND-ETH SLP", icon: "TRex" },
  { pid: 10, name: "Ample Chicks", symbol: "AMPL-ETH SLP", icon: "Chick" },
  { pid: 11, name: "YFI Whale", symbol: "YFI-ETH SLP", icon: "Whale" },
  { pid: 12, name: "Sushi Party!", symbol: "SUSHI-ETH SLP", icon: "Sushi" },
  { pid: 13, name: "REN Rhino", symbol: "REN-ETH SLP", icon: "Rhinoceros" },
  { pid: 14, name: "BASED Bull", symbol: "BASED-sUSD SLP", icon: "Ox" },
  { pid: 15, name: "SRM Shark", symbol: "SRM-ETH SLP", icon: "Shark" },
  { pid: 16, name: "YAMv2 (Old)", symbol: "YAMv2-ETH SLP", icon: "Yam" },
  { pid: 17, name: "CRV Crocodile", symbol: "CRV-ETH SLP", icon: "Crocodile" },
  { pid: 18, name: "UNI Unicorn", symbol: "UNI-ETH SLP", icon: "Unicorn" },
  { pid: 19, name: "Chef's Menu", symbol: "xSUSHI-ETH SLP", icon: "Chef" },
  { pid: 20, name: "Chef's Menu", symbol: "cDAI-DAI SLP", icon: "Chef" },
  { pid: 21, name: "BitCorn", symbol: "WBTC-ETH SLP", icon: "Corn" },
  { pid: 22, name: "Onsen Mid", symbol: "CREAM-ETH SLP", icon: "HotSprings" },
  { pid: 22, name: "Chef's Menu", symbol: "CREAM-ETH SLP", icon: "Chef" },
  { pid: 23, name: "Chef's Menu", symbol: "MEME-ETH SLP", icon: "Chef" },
  { pid: 24, name: "Chef's Menu", symbol: "wNXM-ETH SLP", icon: "Chef" },
  { pid: 25, name: "Yearn Synergy", symbol: "yUSD-ETH", icon: "Cyclone" },
  { pid: 25, name: "Chef's Menu", symbol: "yUSD-ETH SLP", icon: "Chef" },
  { pid: 26, name: "Chef's Menu", symbol: "yUSD-WBTC SLP", icon: "Chef" },
  { pid: 27, name: "Chef's Menu", symbol: "CRO-ETH SLP", icon: "Chef" },
  { pid: 28, name: "Chef's Menu", symbol: "renBTC-WBTC SLP", icon: "Chef" },
  { pid: 31, name: "Onsen Mid", symbol: "HEGIC-ETH SLP", icon: "HotSprings" },
  { pid: 31, name: "Chef's Menu", symbol: "HEGIC-ETH SLP", icon: "Chef" },
  { pid: 32, name: "Chef's Menu", symbol: "wBTC-tBTC SLP", icon: "Chef" },
  { pid: 33, name: "Onsen Mid", symbol: "MKR-ETH SLP", icon: "HotSprings" },
  { pid: 33, name: "Chef's Menu", symbol: "MKR-ETH SLP", icon: "Chef" },
  { pid: 34, name: "Chef's Menu", symbol: "CORE-ETH SLP", icon: "Chef" },
  { pid: 35, name: "Onsen Low", symbol: "PICKLE-ETH SLP", icon: "HotSprings" },
  { pid: 35, name: "Chef's Menu", symbol: "PICKLE-ETH SLP", icon: "Chef" },
  { pid: 36, name: "Onsen Mid", symbol: "OMG-ETH SLP", icon: "HotSprings" },
  { pid: 36, name: "Chef's Menu", symbol: "OMG-ETH SLP", icon: "Chef" },
  { pid: 37, name: "Aave Boar", symbol: "AAVE-ETH SLP", icon: "Boar" },
  { pid: 37, name: "Chef's Menu", symbol: "AAVE-ETH SLP", icon: "Chef" },
  { pid: 38, name: "Chef's Menu", symbol: "AMP-ETH SLP", icon: "Chef" },
  { pid: 39, name: "Chef's Menu", symbol: "xSUSHI-USDC SLP", icon: "Chef" },
  { pid: 40, name: "Chef's Menu", symbol: "GHST-ETH SLP", icon: "Chef" },
  { pid: 41, name: "Chef's Menu", symbol: "RARI-ETH SLP", icon: "Chef" },
  { pid: 42, name: "Onsen Low", symbol: "DPI-ETH SLP", icon: "HotSprings" },
  { pid: 42, name: "Chef's Menu", symbol: "DPI-ETH SLP", icon: "Chef" },
  { pid: 43, name: "Chef's Menu", symbol: "vBTC-tBTC SLP", icon: "Chef" },
  { pid: 44, name: "YAM", symbol: "YAM-ETH SLP", icon: "Yam" },
  { pid: 46, name: "Chef's Menu", symbol: "FARM-ETH SLP", icon: "Chef" },
  { pid: 47, name: "Chef's Menu", symbol: "renBTC-ETH SLP", icon: "Chef" },
  { pid: 48, name: "Onsen Gem", symbol: "DOUGH-ETH SLP", icon: "HotSprings" },
  { pid: 48, name: "Chef's Menu", symbol: "DOUGH-ETH SLP", icon: "Chef" },
  { pid: 49, name: "Chef's Menu", symbol: "STAKE-ETH SLP", icon: "Chef" },
  { pid: 50, name: "Chef's Menu", symbol: "RSR-ETH SLP", icon: "Chef" },
  { pid: 51, name: "Chef's Menu", symbol: "tBTC-ETH SLP", icon: "Chef" },
  { pid: 52, name: "Chef's Menu", symbol: "AUDIO-ETH SLP", icon: "Chef" },
  { pid: 53, name: "Onsen Low", symbol: "AKRO-ETH SLP", icon: "HotSprings" },
  { pid: 53, name: "Chef's Menu", symbol: "AKRO-ETH SLP", icon: "Chef" },
  { pid: 54, name: "Chef's Menu", symbol: "HEZ-ETH SLP", icon: "Chef" },
  { pid: 55, name: "Chef's Menu", symbol: "YAX-ETH SLP", icon: "Chef" },
  { pid: 56, name: "Chef's Menu", symbol: "OUSD-USDT SLP", icon: "Chef" },
  { pid: 57, name: "Chef's Menu", symbol: "SURF-ETH SLP", icon: "Chef" },
  { pid: 58, name: "Bee KP3R", symbol: "KP3R-ETH SLP", icon: "Honeybee" },
  { pid: 58, name: "Chef's Menu", symbol: "KP3R-ETH SLP", icon: "Chef" },
  { pid: 59, name: "Onsen Gem", symbol: "SEEN-ETH SLP", icon: "HotSprings" },
  { pid: 59, name: "Chef's Menu", symbol: "SEEN-ETH SLP", icon: "Chef" },
  { pid: 60, name: "Chef's Menu", symbol: "AXS-ETH SLP", icon: "Chef" },
  { pid: 63, name: "Onsen Mid", symbol: "ESD-ETH SLP", icon: "HotSprings" },
  { pid: 65, name: "Onsen Mid", symbol: "PNK-ETH SLP", icon: "HotSprings" },
  { pid: 66, name: "Onsen Low", symbol: "CVP-ETH SLP", icon: "HotSprings" },
  { pid: 67, name: "Onsen Low", symbol: "YETI-ETH SLP", icon: "HotSprings" },
  { pid: 68, name: "Onsen Gem", symbol: "ARCH-ETH SLP", icon: "HotSprings" },
  { pid: 69, name: "Onsen Mid", symbol: "INJ-ETH SLP", icon: "HotSprings" },
  { pid: 70, name: "Onsen Low", symbol: "BOR-ETH SLP", icon: "HotSprings" },
  { pid: 71, name: "Onsen Low", symbol: "SFI-ETH SLP", icon: "HotSprings" },
  { pid: 72, name: "Onsen Gem", symbol: "DFD-ETH SLP", icon: "HotSprings" },
  { pid: 73, name: "Onsen Low", symbol: "BADGER-WBTC SLP", icon: "HotSprings" },
  { pid: 74, name: "Onsen Low", symbol: "zLOT-ETH SLP", icon: "HotSprings" },
  { pid: 75, name: "Onsen Low", symbol: "INDEX-ETH SLP", icon: "HotSprings" },
  { pid: 76, name: "Onsen Gem", symbol: "SWAG-ETH SLP", icon: "HotSprings" },
  { pid: 77, name: "Onsen Gem", symbol: "JRT-ETH SLP", icon: "HotSprings" },
  { pid: 78, name: "Onsen Gem", symbol: "UWL-ETH", icon: "HotSprings" },
  { pid: 79, name: "Onsen Gem", symbol: "ICHI-ETH SLP", icon: "HotSprings" },
  { pid: 80, name: "Onsen Gem", symbol: "ROPE-ETH SLP", icon: "HotSprings" },
  { pid: 81, name: "Onsen Low", symbol: "oBTC-ETH SLP", icon: "HotSprings" },
  { pid: 82, name: "Onsen Low", symbol: "mbBASED-ETH SLP", icon: "HotSprings" },
  { pid: 83, name: "Onsen Mid", symbol: "DSD-USDC SLP", icon: "HotSprings" },
  { pid: 84, name: "Onsen Gem", symbol: "nTRUMP-DAI SLP", icon: "HotSprings" },
  { pid: 85, name: "Onsen Mid", symbol: "UST-ETH SLP", icon: "HotSprings" },
  { pid: 86, name: "Onsen Low", symbol: "FNX-ETH SLP", icon: "HotSprings" },
  { pid: 87, name: "Onsen Gem", symbol: "BCP-ETH SLP", icon: "HotSprings" },
  { pid: 88, name: "Onsen Gem", symbol: "YPIE-ETH SLP", icon: "HotSprings" },
  { pid: 89, name: "Onsen Gem", symbol: "DEFI+L-ETH SLP", icon: "HotSprings" },
  { pid: 90, name: "Onsen Gem", symbol: "BASE-ETH SLP", icon: "HotSprings" },
  { pid: 91, name: "Onsen Gem", symbol: "DDX-USDC SLP", icon: "HotSprings" },
  { pid: 92, name: "Onsen Low", symbol: "MPH-ETH SLP", icon: "HotSprings" },
  { pid: 93, name: "Onsen Gem", symbol: "FRONT-USDT SLP", icon: "HotSprings" },
  { pid: 94, name: "Onsen Gem", symbol: "UOP-ETH SLP", icon: "HotSprings" },
  { pid: 95, name: "Onsen Low", symbol: "TRU-ETH SLP", icon: "HotSprings" },
  { pid: 96, name: "Onsen Mid", symbol: "ALPHA-ETH SLP", icon: "HotSprings" },
  { pid: 97, name: "Onsen Gem", symbol: "ALPA-ETH SLP", icon: "HotSprings" },
  { pid: 98, name: "Onsen Low", symbol: "CRETH2-ETH SLP", icon: "HotSprings" },
  { pid: 99, name: "Onsen Low", symbol: "DUSD-ETH SLP", icon: "HotSprings" },
  { pid: 100, name: "Onsen Mid", symbol: "ANTv2-ETH SLP", icon: "HotSprings" },
  { pid: 101, name: "COVER Shield", symbol: "COVER-ETH SLP", icon: "Shield" },
];
